-- Source-attributed, read-only, non-partner examples for BARBERCRAFT discovery QA.
-- No original photographs, branded thumbnails, copied descriptions, employee accounts, or booking access.
create table if not exists public.bc_discovery_salon_samples(
 id uuid primary key default gen_random_uuid(),
 name text not null,
 address text not null,
 city text not null default 'București',
 county text not null default 'București',
 sector text not null,
 source_url text not null unique,
 services jsonb not null default '[]'::jsonb,
 publicly_listed_team jsonb not null default '[]'::jsonb,
 source_checked date not null default current_date,
 is_partner boolean not null default false check(is_partner=false),
 booking_enabled boolean not null default false check(booking_enabled=false),
 photo_permission boolean not null default false check(photo_permission=false)
);
alter table public.bc_discovery_salon_samples enable row level security;
revoke all on public.bc_discovery_salon_samples from public,anon,authenticated;
grant select on public.bc_discovery_salon_samples to anon,authenticated;
drop policy if exists bc_sample_public_preview on public.bc_discovery_salon_samples;
create policy bc_sample_public_preview on public.bc_discovery_salon_samples for select
 to anon,authenticated using(true);
insert into public.bc_discovery_salon_samples(name,address,city,county,sector,source_url,services,publicly_listed_team)
values
('4MEN','Bulevardul Iuliu Maniu nr 57, București 061087','București','București','Sector 6','https://mero.ro/p/4men','[{"name":"Spălat + tuns + aranjat","price":"80–100 lei","duration":"45–60 min"},{"name":"Tuns + barbă + spălat","price":"100–120 lei","duration":"60 min"},{"name":"Aranjat barbă","price":"40 lei","duration":"20–30 min"},{"name":"Sprâncene","price":"30 lei","duration":"15 min"}]'::jsonb,'["Nistor Daniel","Ștefan Stinga","Ivan"]'::jsonb),
('Most Wanted','Str. Virtuții 7, bloc R3, scara 2, București','București','București','Sector 6','https://mero.ro/p/most-wanted','[{"name":"Tuns","price":"80–120 lei","duration":"40–60 min"},{"name":"Tuns + barbă","price":"80–130 lei","duration":"45–60 min"},{"name":"Tuns barbă","price":"30–50 lei","duration":"15–30 min"},{"name":"Tuns taper","price":"50 lei","duration":"25 min"},{"name":"Păr lung","price":"150 lei","duration":"60 min"}]'::jsonb,'["Vlad Andrei","Robert Munteanu","Andrei Iulian Țițirigă"]'::jsonb),
('R Style Barbershop','Calea Crângași 46, București','București','București','Sector 6','https://mero.ro/p/r-style-barbershop','[{"name":"Tuns + aranjat","price":"60–70 lei","duration":"40 min"},{"name":"Tuns + barbă + contur","price":"90–100 lei","duration":"50 min"},{"name":"Barbă + contur","price":"30 lei","duration":"20 min"},{"name":"Spălat","price":"10 lei","duration":"5 min"}]'::jsonb,'["Răzvan Andrei","Adnan Al_arabe","Robert Bogdan"]'::jsonb),
('Crown Barbershop','Drumul Taberei 62, București','București','București','Sector 6','https://mero.ro/p/crown-barbershop-58cc','[{"name":"Tuns","price":"70 lei","duration":"45 min"},{"name":"Tuns + barbă","price":"90 lei","duration":"45 min"},{"name":"Barbă","price":"35 lei","duration":"15 min"},{"name":"Tuns + spălat","price":"80 lei","duration":"45 min"},{"name":"Tuns + barbă + spălat","price":"100 lei","duration":"60 min"}]'::jsonb,'["Costin Ionuț","Cristian Stavăr"]'::jsonb),
('WEST BARBER SHOP Militari','Bulevardul Iuliu Maniu 69, Sector 6, București','București','București','Sector 6','https://mero.ro/p/west-barber-shop-militari','[{"name":"Tuns High Level","price":"80–100 lei","duration":"40–60 min"},{"name":"Tuns + barbă","price":"110–160 lei","duration":"60–80 min"},{"name":"Contur barbă","price":"15–30 lei","duration":"5 min"},{"name":"Pensat brici","price":"20 lei","duration":"10 min"}]'::jsonb,'["Bogdan Nicolin"]'::jsonb),
('Victoria Barbershop','Strada Buzești 22, București','București','București','Sector 1','https://mero.ro/p/victoria-barbershop','[{"name":"Tuns + styling","price":"70 lei","duration":"30–45 min"},{"name":"Skin fade + spălat","price":"70–80 lei","duration":"30–45 min"},{"name":"Skin fade + barbă","price":"100 lei","duration":"60 min"},{"name":"Barbă","price":"45 lei","duration":"30 min"}]'::jsonb,'["Vali Badea","Dima V"]'::jsonb),
('HAIR GARAGE BARBER SHOP','Jiului 2–4, bloc C1, București','București','București','Sector 1','https://mero.ro/p/garage-barber-shop','[{"name":"Tuns Fade","price":"75 lei","duration":"50–60 min"},{"name":"Tuns Clasic","price":"60 lei","duration":"30 min"},{"name":"Tuns barbă și contur","price":"40 lei","duration":"20 min"},{"name":"Masaj capilar","price":"15 lei","duration":"10 min"},{"name":"Vopsit barbă","price":"20 lei","duration":"20 min"}]'::jsonb,'[]'::jsonb),
('Barber Băneasa','Bulevardul Aerogării 14, Sector 1, București','București','București','Sector 1','https://mero.ro/p/gentlemans-barberbaneasa','[{"name":"Tuns și stilizat","price":"70 lei","duration":"30 min"},{"name":"Schimbare de look","price":"100 lei","duration":"90 min"},{"name":"Aranjat barbă","price":"40 lei","duration":"30 min"},{"name":"Pachet Haircut","price":"90 lei","duration":"50 min"}]'::jsonb,'[]'::jsonb),
('BJH Studio Barber&Beauty','Strada Lizeanu 7, Sector 2, București','București','București','Sector 2','https://mero.ro/p/bjh-studio-barber-beauty','[{"name":"Skin fade + styling","price":"80 lei","duration":"45 min"},{"name":"Tuns clasic + styling","price":"60 lei","duration":"30 min"},{"name":"Tuns copii + styling","price":"70 lei","duration":"30 min"},{"name":"Pachet Barber Jack Hat","price":"180 lei","duration":"75 min"}]'::jsonb,'["Ștefan Coman","Adrian Roban","Radu Prioteasa"]'::jsonb),
('Salon Marian Cotoi București','Strada Austrului 54, Sector 2, București','București','București','Sector 2','https://mero.ro/p/salon-marian-cotoi-bucuresti','[{"name":"Tuns bărbați clasic","price":"100 lei","duration":"30 min"},{"name":"Tuns Fade","price":"120 lei","duration":"60 min"}]'::jsonb,'[]'::jsonb),
('Frizeria București — Armenească','Strada Italiană 1, București','București','București','Sector 2','https://mero.ro/p/frizeria-bucuresti-armeneasca','[{"name":"Tuns + spălat + masaj","price":"92 lei","duration":"45 min"},{"name":"Tuns + barbă","price":"102 lei","duration":"45 min"},{"name":"Tuns zero","price":"62 lei","duration":"30 min"},{"name":"Tuns barbă","price":"35 lei","duration":"25 min"}]'::jsonb,'[]'::jsonb),
('Fresh Salon','Strada Râmnicu Vâlcea 11, București','București','București','Sector 3','https://mero.ro/p/fresh-salon-24bb','[{"name":"Tuns clasic","price":"70 lei","duration":"30 min"},{"name":"Tuns + spălat","price":"80–110 lei","duration":"40 min"},{"name":"Tuns barbă","price":"30–40 lei","duration":"20 min"},{"name":"Tuns + barbă + spălat","price":"110–130 lei","duration":"60 min"}]'::jsonb,'[]'::jsonb),
('Frizeria 21','Bulevardul Theodor Pallady 35, București','București','București','Sector 3','https://mero.ro/p/frizeria-21','[{"name":"Tuns","price":"70–90 lei","duration":"60 min"},{"name":"Barbă + contur","price":"30–50 lei","duration":"30–60 min"},{"name":"Tuns + barbă","price":"90–110 lei","duration":"60 min"}]'::jsonb,'["Florin Gherman"]'::jsonb),
('Different Salon','Calea Călărași 169, București','București','București','Sector 3','https://mero.ro/p/different-salon','[{"name":"Tuns bărbați","price":"165–180 lei","duration":"45–60 min"},{"name":"Tuns + barbă","price":"190 lei","duration":"60 min"},{"name":"Tuns damă","price":"240–290 lei","duration":"60–90 min"}]'::jsonb,'[]'::jsonb),
('Smart Hair Salon','Bulevardul Alexandru Obregia 6, Sector 4, București','București','București','Sector 4','https://mero.ro/p/smart-hair-salon','[{"name":"Tuns clasic","price":"50 lei","duration":"30 min"},{"name":"Tuns skin fade","price":"60 lei","duration":"60 min"},{"name":"Tuns barbă","price":"30 lei","duration":"30 min"},{"name":"Tuns + barbă","price":"90 lei","duration":"60 min"}]'::jsonb,'["Mirela M","Alexandra G","Alex D"]'::jsonb),
('Golden Barbershop','Șoseaua Berceni 17, București','București','București','Sector 4','https://mero.ro/p/golden-barbershop','[{"name":"Pachet tuns + barbă","price":"110–120 lei","duration":"60 min"},{"name":"Tuns","price":"80–110 lei","duration":"40–60 min"},{"name":"Barbă","price":"30 lei","duration":"20 min"},{"name":"Vopsit barbă","price":"30 lei","duration":"5 min"}]'::jsonb,'[]'::jsonb),
('Iuli','Bulevardul Alexandru Obregia 38A, București','București','București','Sector 4','https://mero.ro/p/iuli-0619','[{"name":"Tuns + aranjat","price":"90 lei","duration":"30 min"},{"name":"Tuns + barbă","price":"130 lei","duration":"60 min"},{"name":"Tuns barbă","price":"50 lei","duration":"30 min"}]'::jsonb,'[]'::jsonb),
('Just Men 13 Septembrie','Strada Mihail Sebastian 136, București','București','București','Sector 5','https://mero.ro/p/just-men-13-septembrie','[{"name":"Tuns + styling","price":"65–80 lei","duration":"30 min"},{"name":"Tuns + barbă","price":"100–110 lei","duration":"60 min"},{"name":"Tuns barbă","price":"25 lei","duration":"15 min"},{"name":"Pachet tuns + barbă + spălat","price":"110–120 lei","duration":"60 min"}]'::jsonb,'["David Calina"]'::jsonb),
('Men''s World Barbershop','Calea 13 Septembrie 221–225, Prosper Mall, București','București','București','Sector 5','https://mero.ro/p/men-s-world-barbersop','[{"name":"Tuns clasic","price":"50 lei","duration":"30 min"},{"name":"Tuns Skin Fade","price":"60 lei","duration":"30 min"},{"name":"Tuns barbă","price":"20 lei","duration":"15 min"},{"name":"Pachet Relaxare","price":"120 lei","duration":"75 min"}]'::jsonb,'["Marius Razvan"]'::jsonb),
('Obsess up','Strada Mihail Sebastian 15, București','București','București','Sector 5','https://mero.ro/p/obsess-up','[{"name":"Tuns cu spălat","price":"70–110 lei","duration":"45 min"},{"name":"Tuns + barbă + spălat","price":"90–135 lei","duration":"60 min"},{"name":"Barbă + contur","price":"30–40 lei","duration":"15 min"},{"name":"Masaj capilar","price":"20 lei","duration":"10 min"}]'::jsonb,'[]'::jsonb)
on conflict(source_url) do update set name=excluded.name,address=excluded.address,sector=excluded.sector,
 services=excluded.services,publicly_listed_team=excluded.publicly_listed_team,source_checked=current_date;
